Repository robolectric/robolectric, pull requests merged in 2019-02, with the labels that each got.

#4559 Run sandboxed tests on dedicated sandbox thread
  junit/build.gradle
  junit/src/main/java/org/robolectric/internal/SandboxTestRunner.java
  junit/src/main/java/org/robolectric/internal/TimeLimitedStatement.java
  robolectric/src/main/java/org/robolectric/ApkLoader.java
  robolectric/src/main/java/org/robolectric/RobolectricTestRunner.java
  robolectric/src/main/java/org/robolectric/android/internal/AndroidEnvironment.java
  robolectric/src/main/java/org/robolectric/internal/AndroidSandbox.java
  robolectric/src/main/java/org/robolectric/internal/Environment.java
  robolectric/src/main/java/org/robolectric/internal/ParallelUniverseInterface.java
  robolectric/src/main/java/org/robolectric/internal/ResourcesMode.java
  robolectric/src/main/java/org/robolectric/internal/SandboxFactory.java
  robolectric/src/main/java/org/robolectric/internal/SdkEnvironment.java
  robolectric/src/test/java/org/robolectric/BootstrapDeferringRobolectricTestRunner.java
  robolectric/src/test/java/org/robolectric/RobolectricTestRunnerTest.java
  robolectric/src/test/java/org/robolectric/SingleSdkRobolectricTestRunner.java
  robolectric/src/test/java/org/robolectric/TestRunnerSequenceTest.java
  robolectric/src/test/java/org/robolectric/android/internal/AndroidEnvironmentCreateApplicationTest.java
  robolectric/src/test/java/org/robolectric/android/internal/AndroidEnvironmentTest.java
  robolectric/src/test/java/org/robolectric/android/internal/ParallelUniverseCreateApplicationTest.java
  robolectric/src/test/java/org/robolectric/internal/bytecode/AndroidSandboxClassLoaderTest.java
  sandbox/build.gradle
  sandbox/src/main/java/org/robolectric/internal/bytecode/RobolectricInternals.java
  sandbox/src/main/java/org/robolectric/internal/bytecode/Sandbox.java
  shadows/framework/src/main/java/org/robolectric/RuntimeEnvironment.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowLooper.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowPackageManager.java
  utils/reflector/src/main/java/org/robolectric/util/reflector/UnsafeAccess.java
  utils/src/main/java/org/robolectric/util/inject/Injector.java
  utils/src/main/java/org/robolectric/util/inject/PluginFinder.java
  utils/src/test/java/org/robolectric/util/inject/InjectorTest.java
  utils/src/test/java/org/robolectric/util/inject/MyServiceFinderAdapter.java
Labels: API change, cla: yes

#4618 add missing shadow of MediaPlayer.setDataSource(MediaDataSource)
  robolectric/src/test/java/org/robolectric/shadows/ShadowMediaPlayerTest.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowMediaPlayer.java
  shadows/framework/src/main/java/org/robolectric/shadows/util/DataSource.java
Labels: contribution

#4597 Add ShadowBluetoothDevice.connectGatt() with transport overload argument.
  robolectric/src/test/java/org/robolectric/shadows/ShadowBluetoothDeviceTest.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowBluetoothDevice.java
Labels: contribution

#4617 Revert to Gradle 4.10.3 and AGP 3.3.1
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/RoboJavaModulePlugin.groovy
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: cla: yes

#4638 4.2 released
  README.md
Labels: cla: yes

#4636 Added missing function to set layertype in ShadowRenderNode
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowRenderNode.java
Labels: contribution

#4664 Don't call Shadows.shadowOf() from within shadows.
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowActivity.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowBluetoothDevice.java
Labels: cla: yes

#4642 Allow delivering broadcasts by class name.
  robolectric/src/test/java/org/robolectric/shadows/ShadowContextWrapperTest.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowInstrumentation.java
Labels: contribution
