Repository robolectric/robolectric, pull requests merged in 2019-03, with the labels that each got.

#4645 Use 'sneaky throw' technique instead of Unsafe
  junit/src/main/java/org/robolectric/internal/SandboxTestRunner.java
  sandbox/src/main/java/org/robolectric/internal/bytecode/Sandbox.java
  utils/reflector/src/main/java/org/robolectric/util/reflector/UnsafeAccess.java
  utils/src/main/java/org/robolectric/util/Util.java
  utils/src/main/java/org/robolectric/util/inject/Injector.java
Labels: cla: yes

#4648 Add method to ShadowContextWrapper to expose the options of the most recently started activity
  robolectric/src/test/java/org/robolectric/shadows/ShadowContextWrapperTest.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowContextWrapper.java
Labels: contribution

#4738 Aggregate test results from all projects.
  build.gradle
  buildSrc/src/main/groovy/RoboJavaModulePlugin.groovy
Labels: cla: yes

#4764 Run integration tests only for the set of robolectric.enabledSdks.
  buildSrc/src/main/groovy/RoboJavaModulePlugin.groovy
  buildSrc/src/main/groovy/org/robolectric/gradle/AndroidProjectConfigPlugin.groovy
  integration_tests/agp/build.gradle
  integration_tests/androidx/build.gradle
  integration_tests/androidx_test/build.gradle
  integration_tests/ctesque/build.gradle
Labels: cla: yes

#4795 Fix test whitespace weirdness on windows/jdk 9.
  robolectric/src/test/java/org/robolectric/shadows/ShadowViewGroupTest.java
Labels: @hide, cla: yes
