Repository robolectric/robolectric, pull requests merged in 2019-01, with the labels that each got.

#4382 Fix build. Turn off warnings for non-framework shadows.
  pluginapi/build.gradle
  shadows/framework/build.gradle
  shadows/httpclient/build.gradle
  shadows/playservices/build.gradle
  shadows/supportv4/build.gradle
  utils/build.gradle
Labels: @hide, cla: yes

#4323 Remove unnecessary @Override SandboxTestRunner.runChild().
  junit/src/main/java/org/robolectric/internal/SandboxTestRunner.java
Labels: @hide, cla: yes, cleanup

#4502 Bump to guava 27.0.1-jre.
  integration_tests/ctesque/build.gradle
  processor/build.gradle
  resources/build.gradle
  robolectric/build.gradle
  sandbox/build.gradle
  shadows/playservices/build.gradle
Labels: cla: yes

#4394 Extract Sdk from SdkConfig
  junit/src/main/java/org/robolectric/internal/SandboxTestRunner.java
  pluginapi/src/main/java/org/robolectric/internal/SdkConfig.java
  pluginapi/src/main/java/org/robolectric/pluginapi/Sdk.java
  pluginapi/src/main/java/org/robolectric/pluginapi/SdkPicker.java
  pluginapi/src/main/java/org/robolectric/pluginapi/SdkProvider.java
  plugins/maven-dependency-resolver/src/main/java/org/robolectric/internal/dependency/MavenDependencyResolver.java
  robolectric/src/main/java/org/robolectric/ApkLoader.java
  robolectric/src/main/java/org/robolectric/RobolectricTestRunner.java
  robolectric/src/main/java/org/robolectric/android/internal/ParallelUniverse.java
  robolectric/src/main/java/org/robolectric/internal/AndroidConfigurer.java
  robolectric/src/main/java/org/robolectric/internal/ParallelUniverseInterface.java
  robolectric/src/main/java/org/robolectric/internal/SandboxFactory.java
  robolectric/src/main/java/org/robolectric/internal/SdkEnvironment.java
  robolectric/src/main/java/org/robolectric/plugins/DefaultSdkPicker.java
  robolectric/src/main/java/org/robolectric/plugins/DefaultSdkProvider.java
  robolectric/src/main/java/org/robolectric/plugins/UnknownSdk.java
  robolectric/src/test/java/org/robolectric/BootstrapDeferringRobolectricTestRunner.java
  robolectric/src/test/java/org/robolectric/RobolectricTestRunnerMultiApiTest.java
  robolectric/src/test/java/org/robolectric/RobolectricTestRunnerTest.java
  robolectric/src/test/java/org/robolectric/SingleSdkRobolectricTestRunner.java
  robolectric/src/test/java/org/robolectric/TestRunnerSequenceTest.java
  robolectric/src/test/java/org/robolectric/android/internal/ParallelUniverseTest.java
  robolectric/src/test/java/org/robolectric/internal/bytecode/AndroidSandboxClassLoaderTest.java
  robolectric/src/test/java/org/robolectric/plugins/DefaultSdkPickerTest.java
  robolectric/src/test/java/org/robolectric/util/TestUtil.java
  sandbox/src/main/java/org/robolectric/JarInstrumentor.java
  sandbox/src/test/java/org/robolectric/SandboxClassLoaderTest.java
Labels: cla: yes

#4512 Fix a couple tests on windows.
  robolectric/src/test/java/org/robolectric/internal/BuckManifestFactoryTest.java
  robolectric/src/test/java/org/robolectric/internal/MavenManifestFactoryTest.java
Labels: @hide, cla: yes

#4489 Deprecate addResolveInfoForIntent and add more testing API that will allow easy migration to the new approach.
  robolectric/src/test/java/org/robolectric/shadows/ShadowPackageManagerTest.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowApplicationPackageManager.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowPackageManager.java
Labels: contribution

#4522 ShadowDisplayManager.getSaturationLevel() is now an instance method
  integration_tests/ctesque/src/test/java/android/provider/SettingsTest.java
  robolectric/src/test/java/org/robolectric/shadows/ShadowDisplayManagerTest.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowDisplayManager.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowDisplayManagerGlobal.java
Labels: API change

#4520 Synchronize access to ShadowPendingIntent and ShadowUsageStatsManager fields
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowPendingIntent.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowUsageStatsManager.java
Labels: contribution

#4526 Add API to set isSafeMode in ShadowPackageManager.
  robolectric/src/test/java/org/robolectric/shadows/ShadowPackageManagerTest.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowApplicationPackageManager.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowPackageManager.java
Labels: contribution

#4527 Throw NameNotFoundException from Context.createPackageContext for non-existing packages.
  robolectric/src/test/java/org/robolectric/shadows/ShadowContextImplTest.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowActivityThread.java
Labels: contribution

#4519 Extensible configuration system
  pluginapi/src/main/java/org/robolectric/pluginapi/ConfigMerger.java
  pluginapi/src/main/java/org/robolectric/pluginapi/ConfigurationStrategy.java
  pluginapi/src/main/java/org/robolectric/pluginapi/Configurer.java
  pluginapi/src/main/java/org/robolectric/pluginapi/SdkPicker.java
  robolectric/src/main/java/org/robolectric/ConfigMerger.java
  robolectric/src/main/java/org/robolectric/RobolectricTestRunner.java
  robolectric/src/main/java/org/robolectric/android/internal/ParallelUniverse.java
  robolectric/src/main/java/org/robolectric/config/ConfigurationRegistry.java
  robolectric/src/main/java/org/robolectric/internal/ParallelUniverseInterface.java
  robolectric/src/main/java/org/robolectric/plugins/ConfigConfigurer.java
  robolectric/src/main/java/org/robolectric/plugins/DefaultConfigMerger.java
  robolectric/src/main/java/org/robolectric/plugins/DefaultSdkPicker.java
  robolectric/src/main/java/org/robolectric/plugins/HierarchicalConfigurationStrategy.java
  robolectric/src/main/java/org/robolectric/plugins/PackagePropertiesLoader.java
  robolectric/src/test/java/org/robolectric/BootstrapDeferringRobolectricTestRunner.java
  robolectric/src/test/java/org/robolectric/RobolectricTestRunnerTest.java
  robolectric/src/test/java/org/robolectric/SingleSdkRobolectricTestRunner.java
  robolectric/src/test/java/org/robolectric/android/internal/ParallelUniverseTest.java
  robolectric/src/test/java/org/robolectric/plugins/CustomConfigurerTest.java
  robolectric/src/test/java/org/robolectric/plugins/DefaultSdkPickerTest.java
  robolectric/src/test/java/org/robolectric/plugins/HierarchicalConfigurationStrategyTest.java
  utils/src/main/java/org/robolectric/util/inject/Injector.java
Labels: cla: yes

#4470 TypedArray doesn't need a shadow in binary mode.
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowTypedArray.java
Labels: @hide, cla: yes, performance

#4548 Add ShadowUiModeManager to Robolectric.
  robolectric/src/test/java/org/robolectric/shadows/ShadowUIModeManagerTest.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowUIModeManager.java
Labels: contribution

#4314 Turn off Travis CI.
  .travis.yml
Labels: cla: yes

#4528 Modify ShadowParcel to throw an Error instead of RuntimeException to discourage
  gradle.properties
  robolectric/src/test/java/org/robolectric/shadows/ShadowParcelTest.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowParcel.java
Labels: contribution

#4546 Update to ShadowDevicePolicyManager to allow uses-policy granting.
  robolectric/src/test/java/org/robolectric/shadows/ShadowDevicePolicyManagerTest.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowDevicePolicyManager.java
Labels: contribution

#4551 Count number of times the wakelock was held.
  robolectric/src/test/java/org/robolectric/shadows/ShadowPowerManagerTest.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowPowerManager.java
Labels: contribution

#4550 Adds basic MediaCodec and MediaMuxer shadows to robolectric. The MediaCodec shadow implements basic passthrough asynchronous encoding, and the MediaMuxer shadow muxes input bytes directly to the file without modification.
  robolectric/src/test/java/org/robolectric/shadows/ShadowMediaCodecTest.java
  robolectric/src/test/java/org/robolectric/shadows/ShadowMediaMuxerTest.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowMediaCodec.java
  shadows/framework/src/main/java/org/robolectric/shadows/ShadowMediaMuxer.java
Labels: contribution

#4555 Javadoc cleanup
  build.gradle
  buildSrc/src/main/groovy/RoboJavaModulePlugin.groovy
  gradle.properties
  pluginapi/src/main/java/org/robolectric/pluginapi/ExtensionPoint.java
  pluginapi/src/main/java/org/robolectric/pluginapi/SdkPicker.java
  pluginapi/src/main/java/org/robolectric/pluginapi/SdkProvider.java
  pluginapi/src/main/java/org/robolectric/pluginapi/config/ConfigurationStrategy.java
  pluginapi/src/main/java/org/robolectric/pluginapi/config/Configurer.java
  pluginapi/src/main/java/org/robolectric/pluginapi/config/GlobalConfigProvider.java
  pluginapi/src/main/java/org/robolectric/pluginapi/package-info.java
  robolectric/src/main/java/org/robolectric/LegacyDependencyResolver.java
  robolectric/src/main/java/org/robolectric/RobolectricTestRunner.java
  robolectric/src/main/java/org/robolectric/android/internal/ParallelUniverse.java
  robolectric/src/main/java/org/robolectric/config/ConfigurationRegistry.java
  robolectric/src/main/java/org/robolectric/internal/ParallelUniverseInterface.java
  robolectric/src/main/java/org/robolectric/plugins/ConfigConfigurer.java
  robolectric/src/main/java/org/robolectric/plugins/DefaultSdkPicker.java
  robolectric/src/main/java/org/robolectric/plugins/HierarchicalConfigurationStrategy.java
  robolectric/src/main/java/org/robolectric/plugins/PackagePropertiesLoader.java
  robolectric/src/test/java/org/robolectric/BootstrapDeferringRobolectricTestRunner.java
  robolectric/src/test/java/org/robolectric/RobolectricTestRunnerTest.java
  robolectric/src/test/java/org/robolectric/SingleSdkRobolectricTestRunner.java
  robolectric/src/test/java/org/robolectric/plugins/CustomConfigurerTest.java
  robolectric/src/test/java/org/robolectric/plugins/DefaultSdkPickerTest.java
  robolectric/src/test/java/org/robolectric/plugins/HierarchicalConfigurationStrategyTest.java
  shadows/framework/src/main/java/org/robolectric/shadows/NativeBitSet64.java
  utils/reflector/src/main/java/org/robolectric/util/reflector/Accessor.java
  utils/reflector/src/main/java/org/robolectric/util/reflector/ForType.java
  utils/reflector/src/main/java/org/robolectric/util/reflector/Reflector.java
Labels: cla: yes

#4565 Regenerate .ap_, fix tests.
  robolectric/src/test/resources/resources.ap_
  scripts/build-resources.sh
Labels: cla: yes
